export const SET_INDEXLISTS = 'SET_INDEXLISTS';
export const SET_BELONGSBYTYPE = 'SET_BELONGSBYTYPE';

export const SUBMIT_FEEDASSIGN = 'SUBMIT_FEEDASSIGN';
export const SUBMIT_CHAINLIST = 'SUBMIT_CHAINLIST';

export const SET_FLAG_CHAINRESPOND = 'SET_FLAG_CHAINRESPOND';
