export const MOUNT_USERINFO = 'MOUNT_USERINFO';

export const SET_TOKENSTATUS = 'SET_TOKENSTATUS';
export const SET_MESSAGE_SINGLECLOSE = 'SET_MESSAGE_SINGLECLOSE';
export const SET_MESSAGE_BOOLEAN = 'SET_MESSAGE_BOOLEAN';
export const SET_FETCHFLAGS = 'SET_FETCHFLAGS';

export const UPDATE_NOUNSBASIC = 'UPDATE_NOUNSBASIC';
export const UPDATE_USERSBASIC = 'UPDATE_USERSBASIC';

export const AXIOS_SWITCH = 'AXIOS_SWITCH';
