export const SET_INDEXLISTS = 'SET_INDEXLISTS';

export const SUBMIT_FEEDASSIGN = 'SUBMIT_FEEDASSIGN';
export const SUBMIT_CHAINLIST = 'SUBMIT_CHAINLIST';
export const SUBMIT_SHAREDSLIST = 'SUBMIT_SHAREDSLIST';

export const SET_FLAG_CHAINRESPOND = 'SET_FLAG_CHAINRESPOND';
