export const SET_UNITVIEW = 'SET_UNITVIEW';
export const SET_UNITSUBCATE = 'SET_UNITSUBCATE';
export const UNIT_SUBMITTING_SWITCH = 'UNIT_SUBMITTING_SWITCH';
export const SUBMIT_UNITRESPONDSLIST = 'SUBMIT_UNITRESPONDSLIST';
