const UNITS_GENERAL = "UNITS_GENERAL";
const USERS_GENERAL = "USERS_GENERAL";
const MARKS_UNITS = "MARKS_UNITS";
const MARKS_IDLIST_UNITS = "MARKS_IDLIST_UNITS";
const ATTRIBUTION_UNIT = "ATTRIBUTION_UNIT";
const NOUNS_NAME = "NOUNS_NAME";

module.exports = {
  UNITS_GENERAL: UNITS_GENERAL,
  USERS_GENERAL: USERS_GENERAL,
  MARKS_UNITS: MARKS_UNITS,
  MARKS_IDLIST_UNITS: MARKS_IDLIST_UNITS,
  ATTRIBUTION_UNIT: ATTRIBUTION_UNIT,
  NOUNS_NAME: NOUNS_NAME
};
