export const MOUNT_USERINFO = 'MOUNT_USERINFO';

export const UNIT_MOUNT_UNITCURRENT = 'UNIT_MOUNT_UNITCURRENT';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'; //from original example
