export const MOUNT_USERINFO = 'MOUNT_USERINFO';

export const UNIT_MOUNT_UNITCURRENT = 'UNIT_MOUNT_UNITCURRENT';
export const UNIT_SUBMITTING_SWITCH = 'UNIT_SUBMITTING_SWITCH';

export const UPDATE_NOUNSBASIC = 'UPDATE_NOUNSBASIC';
export const UPDATE_USERSBASIC = 'UPDATE_USERSBASIC';

export const AXIOS_SWITCH = 'AXIOS_SWITCH';
