export const SET_TOKENSTATUS = 'SET_TOKENSTATUS';
export const SET_UNITCURRENT = 'SET_UNITCURRENT';
export const SET_UNITINSPIRED = 'SET_UNITINSPIRED';
export const SET_UNITBROAD = 'SET_UNITBROAD';
export const SET_FETCHFLAGS = 'SET_FETCHFLAGS';

export const MOUNT_USERINFO = 'MOUNT_USERINFO';
export const UNIT_SUBMITTING_SWITCH = 'UNIT_SUBMITTING_SWITCH';
export const UNIT_AXIOSINSPIRE_SWITCH = 'UNIT_AXIOSINSPIRE_SWITCH';

export const UPDATE_NOUNSBASIC = 'UPDATE_NOUNSBASIC';
export const UPDATE_USERSBASIC = 'UPDATE_USERSBASIC';

export const AXIOS_SWITCH = 'AXIOS_SWITCH';
