export const UPDATE_USERSHEET = 'UPDATE_USERSHEET';

export const UPDATE_ACCOUNTSET = 'UPDATE_ACCOUNTSET';

export const SET_COGNITION_BELLNOTIFY = 'SET_COGNITION_BELLNOTIFY';

export const SETTING_SUBMITTING_SWITCH = 'SETTING_SUBMITTING_SWITCH';
